# Green Taxi 5-Min Tumbling Window Analysis

This notebook provides analysis of the aggregated taxi data from PostgreSQL.

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Connect to PostgreSQL
engine = create_engine('postgresql://postgres:postgres@localhost:5432/postgres')

def run_query(query):
    return pd.read_sql(query, engine)

### 1. Chronological View

In [8]:
query = """
SELECT window_start, pulocationid, num_trips
FROM trips_per_zone_5min
ORDER BY EXTRACT(HOUR FROM window_start) ASC , window_start ASC
LIMIT 5;
"""
run_query(query)

         window_start  pulocationid  num_trips
0 2025-10-01 00:00:00            75          2
1 2025-10-01 00:05:00            95          4
2 2025-10-01 00:10:00            33          2
3 2025-10-01 00:10:00            66          2
4 2025-10-01 00:10:00            95          2

### 2. Peak Hour Distribution

In [3]:
query = """
SELECT EXTRACT(HOUR FROM window_start) as hour, SUM(num_trips) as total_trips
FROM trips_per_zone_5min
GROUP BY hour
ORDER BY total_trips DESC;
"""
df_peak = run_query(query)
df_peak

    hour  total_trips
0   17.0       8028.0
1   16.0       7272.0
2   18.0       7158.0
3   15.0       6720.0
4   14.0       6136.0
5   19.0       5822.0
6   12.0       5594.0
7    9.0       5484.0
8   13.0       5454.0
9   10.0       5150.0
10  11.0       5116.0
11   8.0       5040.0
12  20.0       4652.0
13   7.0       4204.0
14  21.0       3864.0
15  22.0       3292.0
16  23.0       2654.0
17   6.0       1802.0
18   0.0       1606.0
19   1.0       1032.0
20   2.0        844.0
21   5.0        700.0
22   3.0        626.0
23   4.0        582.0

### 3. Top 10 Busiest Slots

In [ ]:
#Which PULocationID had the most trips in a single 5-minute window?
query = """
SELECT window_start, pulocationid, num_trips
FROM trips_per_zone_5min
ORDER BY num_trips DESC
LIMIT 10;
"""
run_query(query)

         window_start  pulocationid  num_trips
0 2025-10-22 08:40:00            74         30
1 2025-10-20 16:30:00            74         28
2 2025-10-25 17:30:00            74         26
3 2025-10-15 08:45:00            74         26
4 2025-10-08 10:35:00            74         26
5 2025-10-08 08:35:00            74         26
6 2025-10-05 18:05:00            74         24
7 2025-10-26 20:20:00            74         24
8 2025-10-01 08:40:00            74         24
9 2025-10-05 17:00:00            74         24

### Question 5: Session Window - Longest Streak

Finding the `PULocationID` with the most trips in a single 5-minute session.

In [13]:
query = """
SELECT pulocationid, num_trips, window_start, window_end 
FROM trips_per_zone_sessions 
ORDER BY num_trips DESC 
LIMIT 1;

"""
run_query(query)

   pulocationid  num_trips        window_start          window_end
0            74         81 2025-10-08 06:46:14 2025-10-08 08:27:40

### Question 6: Tumbling Window - Largest Tip

Finding the hour with the highest total tip amount.

In [16]:
query = """
SELECT window_start, window_end, total_tips 
FROM total_tips_per_hour 
ORDER BY total_tips DESC
LIMIT 1;

"""
run_query(query)

         window_start          window_end  total_tips
0 2025-10-30 16:00:00 2025-10-30 17:00:00       507.1